config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get '/signup', to: 'users#new'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token, :activation_token
	before_save :downcase_email
	before_create :create_activation_digest

	validates :username, presence: true, 
						 length: {maximum: 20},
						 uniqueness: {case_sensitive:false}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:true, 
					  length: {maximum: 255}, 
					  format: {with: VALID_EMAIL_REGEX},
					  uniqueness:{case_sensitive: false}

    #uses bcrypt
	has_secure_password
	validates :password, presence: true, length: {minimum: 8}

	# CarrierWave
	mount_uploader :avatar, AvatarUploader
	# Returns encryption of given string
	def User.digest(string)
		cost  = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
													   BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token.
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Creates a new token and updates remember_digest.
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# Returns true if the given token matches the digest
	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

	# Forgets a user
	def forget
		update_attribute(:remember_digest, nil)
	end

	# Activates an account.
	def activate
		update_attribute(:activated, true)
		update_attribute(:activated_at, Time.zone.now)
	end

	# Sends activation email.
	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end
	
	private

	#Converts email to all lowercase.
	def downcase_email
		self.email = email.downcase
	end

	#Creates and assigns activation token and digest
	def create_activation_digest
		self.activation_token = User.new_token
		self.activation_digest = User.digest(activation_token)
	end


end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
	def edit
		user = User.find_by(email: params[:email])
		if user && !user.activated? && user.authenticated?(:activation, params[:id])
			user.activate
			login user 
			flash[:success] = "Account activated!"
			redirect_to user
		else
			flash[:danger] = "Invalid activation link."
			redirect_to root_url
		end
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  #search for user here
  def create
  	@user = User.find_by(email: params[:email].downcase).try(:authenticate, params[:password])
  	if @user
      if @user.activated
    	  login(@user)
  		  remember(@user) unless params[:remember_me].nil?
  		  params[:remember_me] == '1' ? remember_me(@user) : forget(@user)
    	  flash[:success] = "Welcome back!"
  		  redirect_back_or(@user)
    	else
        message = "Account not activated."
        message += "Check your email for the activation link."
    		flash[:danger] = "Invalid email/password combination."
    		redirect_to root_url
    	end
    else
      flash.now[:danger] = "Invalid email/password combination."
      render 'new'
    end
  end

  def destroy

  	logout if logged_in?
  	redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  def show
  	@user = User.find(params[:id])
    @currentUser = current_user
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      @user.send_activation_email
  		#flash[:success] = "Welcome to myreads, "+@user.username+"!"
  		#redirect_to @user
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def edit
    @user  = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Saved changes."
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  	def user_params
  		params.require(:user).permit(:username,:email,:password,:avatar,:password_confirmation)
  	end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless @user == current_user
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
		redirect_to current_user if logged_in?
		@user = User.new
	end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	#Log in the given user.
	def login(user)
		session[:user_id] = user.id
	end

	#Returns the current logged-in user, if any.
	def current_user

		if(user_id = session[:user_id])
			@current_user ||= User.find_by(id: session[:user_id])
		elsif(user_id = cookies.signed[:user_id])
			user = User.find_by(user_id)
			if(user && user.authenticated?(cookies[:remember_token]))
				login(user)
				@current_user = user
			end
		end	
	end

	# Returns true if the user is logged in, false otherwise
	def logged_in?
		!current_user.nil?
	end

	# Forget a persistent session
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)

	end

	# Logs out the current user.
	def logout
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	# Remembers a user in a persistent session.
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end

	def redirect_back_or(default)
		redirect_to session[:forwarding_url] || default
		session.delete(:forwarding_url)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<div id="header" style="width:100%;height:50px;background-color:purple;color:white">
	<h3>myReads</h3>
	<%if logged_in?%>
		<%=link_to "logout", logout_path, method: :delete%>
	<%else%>
		<%=link_to "Signup", signup_path%>
	<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title)%></title><!--add logo later here-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' if logged_in?%>
    <% flash.each do |key, message| %>
      <div class="alert_<%=key%>"><%=message%></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div class="error_box">
		<p class="error_header">The form contains <%=pluralize(@user.errors.count, 'error')%> :</p>
		<ul>
			<%@user.errors.count.times do |i|%>
				<li><%=@user.errors.full_messages[i]%></li>
			<%end%>
		</ul>
	</div>
<%end%>

app/views/users/edit.html.erb
<p class="header">edit<b>Profile</b></p>

<%= render 'shared/error_messages'%>

<%=form_for (@user), html: {class: "signup_form"} do |f|%>

	<%= f.text_field :username, placeholder: "Username", required: true, maxlength: 20%><br />
	<%= f.text_field :email, placeholder: "Email", required: true, maxlength:255%><br />
	<%= image_tag(@user.avatar.small.url) if @user.avatar?%>
	<%= f.file_field :avatar%>
	<%= f.hidden_field :avatar_cache%>
	<%=	f.password_field :password, placeholder: "Password", required: true, minlength: 8,maxlength:25%><br />
	<%= f.password_field :password_confirmation, placeholder: "Password Confirmation", required: true, minlength: 8, maxlength:25%><br />
	<%= f.submit "Save Changes"%>
<%end%>

app/views/users/new.html.erb
<p class="header">my<b>reads</b></p>

<%= render 'shared/error_messages'%>

<%=form_for (@user), html: {class: "signup_form"} do |f|%>
	<%= f.text_field :username, placeholder: "Username", required: true, maxlength: 20%><br />
	<%= f.text_field :email, placeholder: "Email", required: true, maxlength:255%><br />
	<%=	f.password_field :password, placeholder: "Password", required: true, minlength: 8,maxlength:25%><br />
	<%= f.password_field :password_confirmation, placeholder: "Password Confirmation", required: true, minlength: 8, maxlength:25%><br />
	<%= f.submit "Sign Up"%>
<%end%>
<p style="text-align: center">Already a member? <%= link_to 'Login', login_path%></p>

app/views/users/show.html.erb
<% provide(:title, @user.username)%>
<% if @user.avatar?%>
	<span id="user-avatar" style="background:url(<%=@user.avatar.small.url%>)"></span>
<%else%>
	<span id="user-avatar" style="background-color:salmon;"></span>
<%end%>
<h2 id="user-name"><%=@user.username.capitalize%></h2>

<% if logged_in? && @currentUser.id == @user.id%>
	<%= link_to 'edit',edit_user_path, id: "btn"%>
<%end%>

<section class="wrapper">
	<div class="collection-box currently-reading-box">
	</div>
	<h3>Currently Reading</h3>
</section>

<section class="wrapper">
	<div class="collection-box reading-challenge-box">
	</div>
	<h3>Reading Challenge</h3>
</section>

<section class="wrapper">
	<div class="collection-box bookshelves-box">
	</div>
	<h3>Bookshelves</h3>
</section>

app/views/welcome/home.html.erb
<div id="welcome">
<h2 class="header" style="margin:0;color:white;padding-top:100px">my<b>Reads</b></h2>
<h4 style="margin:0;color:white;text-align: center">For the love of a good book.</h4>

<%= link_to 'Sign up with email', signup_path%>
<p>Already a member? <%= link_to 'Login', login_path%></p>
</div>